name: norma_machine
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  font_awesome_flutter: ^10.5.0
  file_picker: ^5.0.0
  permission_handler: ^10.2.0  # Adicione esta linha

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
